[[main]]
name = "Official Discord"
url = "https://discord.gg/zenithsouterreach"
weight = 10

[[main]]
name = "Artists / Makers"
weight = 20

[[main]]
name = "2D Artists"
parent = "Artists / Makers"
url = "/pages/am/2dartists"
weight = 10

[[main]]
name = "3D Artists"
parent = "Artists / Makers"
url = "/pages/am/3dartists"
weight = 20

[[main]]
name = "Makers"
parent = "Artists / Makers"
url = "/pages/am/makers"
weight = 30

[[main]]
name = "Resources"
weight = 30

[[main]]
name = "Lore"
parent = "Resources"
url = "/pages/res/lore"
weight = 10

[[main]]
name = "Art Bases"
parent = "Resources"
url = "/pages/res/artbases"
weight = 9

[[main]]
name = "Guides"
parent = "Resources"
url = "/pages/res/guides"
weight = 8

[[main]]
name = "3D Printing"
parent = "Resources"
url = "/pages/res/3dprinting"
weight = 7

[[main]]
name = "Similar Species"
parent = "Resources"
url = "/pages/res/species"
weight = 6

[[footer]]
name = "Backround by RazzleGazzle"
url = "https://bsky.app/profile/razzlegazz.bsky.social"
weight = 20

[[footer]]
name = "Logo by SirBurnt"
url = "https://x.com/Sir_Burnt"
weight = 10

[[footer]]
name = "Github"
pre = "github"
url = "https://github.com/Vibeshibe/protoinfo"
identifier = "github"
weight = 9999
