[[main]]
name = "Official Discord"
url = "https://discord.gg/zenithsouterreach"
weight = 10

[[main]]
name = "Artists / Makers"
weight = 20

[[main]]
name = "2D Artists"
parent = "Artists / Makers"
url = "/pages/artistsandmakers/2dartists"
weight = 10

[[main]]
name = "3D Artists"
parent = "Artists / Makers"
url = "/pages/artistsandmakers/3dartists"
weight = 20

[[main]]
name = "Makers"
parent = "Artists / Makers"
url = "/pages/artistsandmakers/makers"
weight = 30

[[main]]
name = "Resources"
weight = 30

[[main]]
name = "Lore"
parent = "Resources"
url = "/pages/resources/lore"
weight = 10

[[main]]
name = "Art Bases"
parent = "Resources"
url = "/pages/resources/lore"
weight = 9

[[main]]
name = "Guides"
parent = "Resources"
url = "/pages/resources/guides"
weight = 8

[[main]]
name = "3D Printing"
parent = "Resources"
url = "/pages/resources/3dprinting"
weight = 7

[[main]]
name = "Similar Species"
parent = "Resources"
url = "/pages/resources/species"
weight = 6

[[footer]]
name = "Artwork by YegArtist"
url = "https://x.com/AtlasInu"
weight = 20

[[footer]]
name = "Logo by SirBurnt"
url = "https://x.com/kodadeer"
weight = 10

[[footer]]
name = "Github"
pre = "github"
url = "https://github.com/Vibeshibe/protoinfo"
identifier = "github"
weight = 9999
